FROM qmcgaw/latexdevcontainer
RUN tlmgr update --self && \ 
    tlmgr install \
        collection-fontsrecommended \ 
        collection-latexrecommended \ 
        tempora \ 
        vmargin \ 
        picture \ 
        biblatex \ 
        biblatex-ieee \ 
        biber \ 
        blindtext \ 
        multirow \ 
        paralist \ 
        zed-csp \ 
        cbfonts-fd \ 
        csquotes \ 
        chngcntr \ 
        was \ 
        enumitem \ 
        placeins \ 
        greek-fontenc \ 
        cyrillic \
        lh \
        babel-greek && \ 
    texhash